"""vs004 reply link inbox lease and modality

Revision ID: 22a816a5a08d
Revises: cb8eabda06b9
Create Date: 2026-09-27 22:02:40.380574

Written by hand rather than autogenerated. Alembic finds the column, the foreign
key and the unique constraint, but it never compares CHECK constraints
(app/db/enums.py says so), so the modality widening would have been silently
missing from a generated revision.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22a816a5a08d"
down_revision: str | Sequence[str] | None = "cb8eabda06b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The claim lease (VS-004 plan note C3a). No index: every read of it is by
    # webhook_inbox.id or provider_event_id, both already unique-indexed.
    op.add_column(
        "webhook_inbox", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True)
    )

    # The reply link, and the constraint that makes two replies to one inbound
    # message impossible rather than merely unlikely.
    op.add_column("messages", sa.Column("reply_to_message_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_messages_reply_to_message_id_messages",
        "messages",
        "messages",
        ["reply_to_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "uq_messages_reply_to_message_id", "messages", ["reply_to_message_id"]
    )

    # Widen the modality vocabulary (MessageModality.OTHER), so "store all
    # inbound message types" can include an image or a location. A swapped CHECK
    # is fully reversible, which is exactly why this project uses VARCHAR + CHECK
    # instead of a native ENUM: ALTER TYPE ... ADD VALUE has no downgrade.
    # The BARE name, not "ck_messages_modality_valid": Base.metadata's naming
    # convention ("ck_%(table_name)s_%(constraint_name)s") is applied by
    # drop_constraint too, so passing the rendered name produces
    # "ck_messages_ck_messages_modality_valid" and the DROP fails.
    op.drop_constraint("modality_valid", "messages", type_="check")
    op.create_check_constraint(
        "modality_valid", "messages", "modality IN ('TEXT', 'VOICE_NOTE', 'OTHER')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # This narrowing FAILS if any row already has modality='OTHER', and that is
    # correct: the alternative is silently rewriting a patient's message to a
    # modality it does not have, to make a downgrade succeed. A loud failure
    # tells whoever is downgrading that they have data to decide about first.
    op.drop_constraint("modality_valid", "messages", type_="check")
    op.create_check_constraint("modality_valid", "messages", "modality IN ('TEXT', 'VOICE_NOTE')")

    # FULL names here, unlike the CHECK above, and the asymmetry is real: the
    # "ck" convention is "ck_%(table_name)s_%(constraint_name)s", so a bare name
    # gets rendered through it, while "uq"/"fk" are built from COLUMN names and
    # a string passed to drop_constraint is therefore used verbatim.
    op.drop_constraint("uq_messages_reply_to_message_id", "messages", type_="unique")
    op.drop_constraint("fk_messages_reply_to_message_id_messages", "messages", type_="foreignkey")
    op.drop_column("messages", "reply_to_message_id")

    op.drop_column("webhook_inbox", "locked_until")
