"""vs006 tenant id is opaque text

Written by hand, not autogenerated, so that USING is explicit in both
directions. Decision D1 makes the tenant id an opaque string - probably a clinic
username at the Booking Service, whose format is not decided - so it must never
be parsed. Every tenant_id column becomes TEXT.

PostgreSQL rebuilds the indexes and constraints that use the column as part of
ALTER COLUMN TYPE. Verified on PostgreSQL 16 (plan check U4), and pinned by
tests/db/test_migrations.py::
test_every_tenant_index_and_unique_constraint_survives_the_type_change:

  contacts            ix_contacts_tenant_id            btree
  contact_identities  uq_contact_identities_identity   UNIQUE (tenant_id, channel, external_id)
  conversations       uq_conversations_open            UNIQUE partial, WHERE state <> 'CLOSED'
  messages            ix_messages_tenant_id_conversation_id_created_at   btree
  webhook_inbox       none on tenant_id (uq_webhook_inbox_provider_event_id is untouched)
  dead_letter_jobs    none on tenant_id (ix_dead_letter_jobs_created_at is untouched)

No foreign key references tenant_id. Each ALTER rewrites its table under an
ACCESS EXCLUSIVE lock: fine at these table sizes, and a note for production.

Revision ID: 4f3c8d21a90e
Revises: 22a816a5a08d
Create Date: 2026-09-29

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4f3c8d21a90e"
down_revision: str | Sequence[str] | None = "22a816a5a08d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_COLUMNS = (  # (table, nullable)
    ("contacts", False),
    ("contact_identities", False),
    ("conversations", False),
    ("messages", False),
    ("webhook_inbox", True),
    ("dead_letter_jobs", True),
)


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows keep their tenant as PostgreSQL's canonical uuid text:
    # lowercase and hyphenated. If the configured tenant is spelled any other
    # way (upper case, say) it is now a DIFFERENT tenant and its contacts become
    # invisible. See plan conflict C3 before relying on this on a populated
    # database.
    for table, nullable in TENANT_COLUMNS:
        op.alter_column(
            table,
            "tenant_id",
            existing_type=sa.Uuid(),
            type_=sa.Text(),
            existing_nullable=nullable,
            postgresql_using="tenant_id::text",
        )


def downgrade() -> None:
    """Downgrade schema."""
    # This FAILS if any tenant_id is not uuid-shaped, and that is correct: the
    # alternative is inventing a uuid for a clinic, which is data loss dressed
    # up as a migration. The whole downgrade runs in one transaction, so a
    # failure leaves the database at this revision, unchanged. Same reasoning as
    # VS-004's CHECK narrowing.
    for table, nullable in reversed(TENANT_COLUMNS):
        op.alter_column(
            table,
            "tenant_id",
            existing_type=sa.Text(),
            type_=sa.Uuid(),
            existing_nullable=nullable,
            postgresql_using="tenant_id::uuid",
        )
