"""vs006 agent runs and tool executions

Autogenerated and then reviewed against plan section 5.9. What the review
checked, because autogenerate can silently omit any of it:

  - both CHECK constraints are rendered (autogenerate DOES render them for a
    NEW table, though it never compares them afterwards - see
    app/db/enums.check_constraint);
  - the foreign key is ON DELETE CASCADE, so deleting a run takes its tool rows
    with it and no orphan can outlive its parent;
  - UNIQUE (agent_run_id, sequence), which both fixes the order of a turn's tool
    rows and indexes the foreign key. It is needed because every row of a turn
    is written in ONE transaction and PostgreSQL's now() is constant within a
    transaction, so created_at cannot order them;
  - argument_names is TEXT[] with NO server default: an empty list must be
    written explicitly, never defaulted into existence;
  - the downgrade drops both tables and both indexes.

Neither table has a column that can hold content (hard rule 8). The exact
column sets are pinned by tests/db/test_models.py, so adding a `result` or
`arguments` column means consciously editing that test.

Revision ID: 50a570a315fb
Revises: 4f3c8d21a90e
Create Date: 2026-09-29 10:56:16.469164

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "50a570a315fb"
down_revision: str | Sequence[str] | None = "4f3c8d21a90e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "agent_runs",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("inbox_event_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("inbound_message_id", sa.Uuid(), nullable=False),
        sa.Column("reply_message_id", sa.Uuid(), nullable=True),
        sa.Column("job_try", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("model_calls", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS', 'RETRYABLE', 'PERMANENT')",
            name=op.f("ck_agent_runs_outcome_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index("ix_agent_runs_inbox_event_id", "agent_runs", ["inbox_event_id"], unique=False)
    op.create_index(
        "ix_agent_runs_tenant_id_created_at",
        "agent_runs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "tool_executions",
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("model_call", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("argument_names", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OK', 'INVALID_ARGUMENTS', 'UNKNOWN_TOOL', 'ERROR', 'SKIPPED')",
            name=op.f("ck_tool_executions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tool_executions_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_executions")),
        sa.UniqueConstraint("agent_run_id", "sequence", name="uq_tool_executions_run_sequence"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("tool_executions")
    op.drop_index("ix_agent_runs_tenant_id_created_at", table_name="agent_runs")
    op.drop_index("ix_agent_runs_inbox_event_id", table_name="agent_runs")
    op.drop_table("agent_runs")
