"""vs008 voice notes

Written BY HAND, never autogenerated, for the same two reasons as VS-007's:

  - Alembic's autogenerate never compares CHECK constraints, so
    ck_voice_notes_status_valid would be invisible to it (see
    app/db/enums.check_constraint);
  - the revision id is fixed by the plan, and the migration tests that step
    across this change name it explicitly rather than using "-1".

The DDL was rendered offline before this file was written (plan appendix C) and
the names below are what Alembic actually produced: the CHECK as
`ck_voice_notes_status_valid`, the FK as `fk_voice_notes_message_id_messages`
with ON DELETE CASCADE, the unique constraint as `uq_voice_notes_message_id`,
and the index as `ix_voice_notes_tenant_id_created_at`. `op.f()` wraps each one
so the naming convention in app/db/base.py does not prefix an already-prefixed
name a second time - VS-004's lesson.

**voice_notes holds ids, codes and counts.** No transcript column, no media
URL, no sha256 of the audio, no patient reference (hard rule 8). The transcript
is the patient's message and lives in `messages.text`, under the same retention
and the same access as a typed one; a copy here would be a second place patient
content lives with no retention story of its own.

The FK to `messages` is ON DELETE CASCADE because this is operational state that
dies with its message. The unique constraint on `message_id` is what makes a
retried job - and a duplicated webhook - produce one transcription rather than
two (hard rule 2).

**The downgrade is UNCONDITIONAL, and that is the difference from VS-007's.**
VS-007's downgrade deliberately FAILS while a widened CHECK value is in use,
because narrowing it would mean rewriting a recorded fact. This migration widens
nothing: it only creates a table. Dropping it loses operational bookkeeping - who
transcribed what, how big it was, which model - and loses NO patient content,
because the transcripts are in `messages.text`, which this migration does not
touch. So there is no guard here, and nobody should copy VS-007's without its
reason.

`CREATE TABLE` takes no lock on anything existing. The FK takes a brief
SHARE ROW EXCLUSIVE on `messages` while it is created: fine at this size, and a
note for production.

Revision ID: 7c4e1a9db203
Revises: b919820bf52e
Create Date: 2026-10-01

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c4e1a9db203"
down_revision: str | Sequence[str] | None = "b919820bf52e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "voice_notes",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("inbox_event_id", sa.Uuid(), nullable=False),
        sa.Column("media_id", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=64), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("voice", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'DONE', 'UNCLEAR', 'FAILED')",
            name=op.f("ck_voice_notes_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_voice_notes_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voice_notes")),
        sa.UniqueConstraint("message_id", name=op.f("uq_voice_notes_message_id")),
    )
    op.create_index(
        "ix_voice_notes_tenant_id_created_at",
        "voice_notes",
        ["tenant_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_voice_notes_tenant_id_created_at", "voice_notes")
    op.drop_table("voice_notes")
