"""vs007 booking actions and uncertain tool status

Written BY HAND, never autogenerated, for two reasons:

  - Alembic's autogenerate never compares CHECK constraints, so the widening of
    ck_tool_executions_status_valid is invisible to it (see
    app/db/enums.check_constraint);
  - the revision id is fixed by the plan, and the two migration tests that step
    across this change name it explicitly rather than using "-1".

**The CHECK swap.** `op.drop_constraint`/`op.create_check_constraint` are given the
BARE name `status_valid`. The naming convention in app/db/base.py renders it as
`ck_tool_executions_status_valid` for the DROP and the ADD alike - VS-004's lesson,
re-verified offline before this file was written. Passing the full name would
produce `ck_tool_executions_ck_tool_executions_status_valid`.

It takes a brief ACCESS EXCLUSIVE lock on `tool_executions`: fine at this size, and
a note for production.

**The downgrade FAILS while any tool_executions row is UNCERTAIN or REFUSED, and
that is correct.** The alternative is rewriting a recorded fact - claiming a
booking-changing call whose outcome we never learned was an ERROR - to make a
downgrade succeed. The whole downgrade runs in one transaction, so a failure leaves
the database at this revision. Same reasoning as VS-004's CHECK narrowing.

**booking_actions.** Ids, codes and one operational expiry; no names, no appointment
or slot times, no tool results, no patient reference (hard rule 8). The FK to
conversations is ON DELETE CASCADE because this is operational state that dies with
its conversation. The partial unique index is what makes "the prepared change" a
single thing per conversation.

Revision ID: b919820bf52e
Revises: 50a570a315fb
Create Date: 2026-09-30

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b919820bf52e"
down_revision: str | Sequence[str] | None = "50a570a315fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OLD_TOOL_STATUSES = "status IN ('OK', 'INVALID_ARGUMENTS', 'UNKNOWN_TOOL', 'ERROR', 'SKIPPED')"
NEW_TOOL_STATUSES = (
    "status IN ('OK', 'INVALID_ARGUMENTS', 'UNKNOWN_TOOL', 'ERROR', 'SKIPPED', "
    "'UNCERTAIN', 'REFUSED')"
)


def upgrade() -> None:
    op.drop_constraint("status_valid", "tool_executions", type_="check")
    op.create_check_constraint("status_valid", "tool_executions", NEW_TOOL_STATUSES)

    op.create_table(
        "booking_actions",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("hold_id", sa.String(length=128), nullable=True),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("appointment_id", sa.String(length=128), nullable=True),
        sa.Column("created_by_inbox_event_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_inbound_message_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_inbound_message_id", sa.Uuid(), nullable=True),
        sa.Column("last_idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('BOOK', 'RESCHEDULE', 'CANCEL')",
            name=op.f("ck_booking_actions_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'DONE', 'FAILED', 'UNCERTAIN', 'SUPERSEDED', 'EXPIRED')",
            name=op.f("ck_booking_actions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_booking_actions_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_actions")),
    )
    op.create_index(
        "uq_booking_actions_one_pending",
        "booking_actions",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        "ix_booking_actions_tenant_id_conversation_id_created_at",
        "booking_actions",
        ["tenant_id", "conversation_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_booking_actions_tenant_id_conversation_id_created_at", "booking_actions")
    op.drop_index("uq_booking_actions_one_pending", "booking_actions")
    op.drop_table("booking_actions")

    # FAILS while any tool_executions row is UNCERTAIN or REFUSED. See the module
    # docstring: that is the correct outcome, not a bug to work around.
    op.drop_constraint("status_valid", "tool_executions", type_="check")
    op.create_check_constraint("status_valid", "tool_executions", OLD_TOOL_STATUSES)
